# Site settings
title: Mohit Kulkarni	
description: My website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://github.com/m2kulkarni/m2kulkarni.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mohit Kulkarni
user_description: I'm a "Mathematics and Scientific Computing" student at IIT Kanpur, always searching for the next challenge. Being a freshman at college, I have been immersed in exploring various domains of science and life alike. Current interest areas include <i>Spell-check Algorithms, Cryptocurrency, Music, Getting OK Grades, etc</i>. I hope to do a project(or atleast a blog post) on each of these topics to get a better understanding. But :p<sub>(rocrastination)</sub>.<br/> <big>I would love to talk with you, so feel free to drop a message on any of the social media.</big>
user_title: Student at IIT Kanpur
email: kulkarnimohit01@gmail.com
# twitter_username: lorem_ipsum
# github_username:  m2kulkarni
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-154007714-1"

exclude: ['package.json', 'src' , 'node_modules']

user_title: Student
email: kulkarnimohit01@gmail.com
# twitter_username: lorem_ipsum
# github_username:  m2kulkarni
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-154007714-1"

exclude: ['package.json', 'src' , 'node_modules']
